<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\SilentMoonApp.SharedKernel\SilentMoonApp.SharedKernel.csproj" />
    <ProjectReference Include="..\SilentMoonApp.Domain\SilentMoonApp.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="8.6.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
    <PackageReference Include="Scrutor" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Queries\" />
    <Folder Include="Features\Categories\Commads\" />
    <Folder Include="Features\Courses\Commands\" />
    <Folder Include="Features\Health\Commands\" />
  </ItemGroup>

</Project>
