//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentMoonApp.SharedKernel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilentMoonApp.SharedKernel.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account is temporarily locked. Please try again later..
        /// </summary>
        public static string AuthAccountLocked {
            get {
                return ResourceManager.GetString("AuthAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your email address before signing in..
        /// </summary>
        public static string AuthEmailNotVerified {
            get {
                return ResourceManager.GetString("AuthEmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is incorrect..
        /// </summary>
        public static string AuthInvalidCredentials {
            get {
                return ResourceManager.GetString("AuthInvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The refresh token is invalid or has expired..
        /// </summary>
        public static string AuthInvalidRefreshToken {
            get {
                return ResourceManager.GetString("AuthInvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication is required to access this resource..
        /// </summary>
        public static string AuthUnAuthorized {
            get {
                return ResourceManager.GetString("AuthUnAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is already in use..
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Account with this email already exists. Link the External Provider to the existing account..
        /// </summary>
        public static string ExternalAuthAccountLinkRequired {
            get {
                return ResourceManager.GetString("ExternalAuthAccountLinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Account is not available for sign-in..
        /// </summary>
        public static string ExternalAuthAccountUnavailable {
            get {
                return ResourceManager.GetString("ExternalAuthAccountUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The External Provider did not provide a valid email address..
        /// </summary>
        public static string ExternalAuthEmailRequired {
            get {
                return ResourceManager.GetString("ExternalAuthEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The External Authentication Token is invalid or has expired..
        /// </summary>
        public static string ExternalAuthInvalidProviderToken {
            get {
                return ResourceManager.GetString("ExternalAuthInvalidProviderToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum number of OTP verification attempts has been exceeded..
        /// </summary>
        public static string OtpAttemptsExceeded {
            get {
                return ResourceManager.GetString("OtpAttemptsExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP code is incorrect..
        /// </summary>
        public static string OtpInvalidCode {
            get {
                return ResourceManager.GetString("OtpInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP code is no longer available. Request a new code..
        /// </summary>
        public static string OtpUnavailable {
            get {
                return ResourceManager.GetString("OtpUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The OTP resend request is invalid..
        /// </summary>
        public static string ResendEmailOtpInvalidRequest {
            get {
                return ResourceManager.GetString("ResendEmailOtpInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset request is invalid..
        /// </summary>
        public static string ResetPasswordInvalidRequest {
            get {
                return ResourceManager.GetString("ResetPasswordInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must be different from the current password..
        /// </summary>
        public static string ResetPasswordSameAsCurrentPassword {
            get {
                return ResourceManager.GetString("ResetPasswordSameAsCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file extension, content type, and actual file format do not match..
        /// </summary>
        public static string StorageContentTypeMismatch {
            get {
                return ResourceManager.GetString("StorageContentTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested file was not found..
        /// </summary>
        public static string StorageFileNotFound {
            get {
                return ResourceManager.GetString("StorageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file size exceeds the maximum allowed size of {0} bytes..
        /// </summary>
        public static string StorageFileTooLarge {
            get {
                return ResourceManager.GetString("StorageFileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file extension, content type, and actual file format do not match..
        /// </summary>
        public static string StorageInvalidContentType {
            get {
                return ResourceManager.GetString("StorageInvalidContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file is invalid..
        /// </summary>
        public static string StorageInvalidFile {
            get {
                return ResourceManager.GetString("StorageInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name is invalid or exceeds the maximum allowed character count..
        /// </summary>
        public static string StorageInvalidFileName {
            get {
                return ResourceManager.GetString("StorageInvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The uploaded file type is not supported..
        /// </summary>
        public static string StorageUnsupportedFileType {
            get {
                return ResourceManager.GetString("StorageUnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Username is already in use..
        /// </summary>
        public static string UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is not valid..
        /// </summary>
        public static string ValidationEmailInvalid {
            get {
                return ResourceManager.GetString("ValidationEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required..
        /// </summary>
        public static string ValidationEmailRequired {
            get {
                return ResourceManager.GetString("ValidationEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occurred..
        /// </summary>
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        public static string ValidationPasswordRequired {
            get {
                return ResourceManager.GetString("ValidationPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address has already been verified..
        /// </summary>
        public static string VerifyEmailAlreadyVerified {
            get {
                return ResourceManager.GetString("VerifyEmailAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation request is invalid..
        /// </summary>
        public static string VerifyEmailInvalidConfirmation {
            get {
                return ResourceManager.GetString("VerifyEmailInvalidConfirmation", resourceCulture);
            }
        }
    }
}
