//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentMoonApp.SharedKernel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilentMoonApp.SharedKernel.Resources.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string DefaultUserName {
            get {
                return ResourceManager.GetString("DefaultUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Thought.
        /// </summary>
        public static string HomeDailyThought {
            get {
                return ResourceManager.GetString("HomeDailyThought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        public static string HomeFeaturedSleep {
            get {
                return ResourceManager.GetString("HomeFeaturedSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Afternoon.
        /// </summary>
        public static string HomeGreetingAfternoon {
            get {
                return ResourceManager.GetString("HomeGreetingAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a mindful break for yourself.
        /// </summary>
        public static string HomeGreetingAfternoonMessage {
            get {
                return ResourceManager.GetString("HomeGreetingAfternoonMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Evening.
        /// </summary>
        public static string HomeGreetingEvening {
            get {
                return ResourceManager.GetString("HomeGreetingEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow down and relax your mind.
        /// </summary>
        public static string HomeGreetingEveningMessage {
            get {
                return ResourceManager.GetString("HomeGreetingEveningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Morning.
        /// </summary>
        public static string HomeGreetingMorning {
            get {
                return ResourceManager.GetString("HomeGreetingMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We wish you have a good day.
        /// </summary>
        public static string HomeGreetingMorningMessage {
            get {
                return ResourceManager.GetString("HomeGreetingMorningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Night.
        /// </summary>
        public static string HomeGreetingNight {
            get {
                return ResourceManager.GetString("HomeGreetingNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest well and clear your mind.
        /// </summary>
        public static string HomeGreetingNightMessage {
            get {
                return ResourceManager.GetString("HomeGreetingNightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Meditations.
        /// </summary>
        public static string HomePopularMeditations {
            get {
                return ResourceManager.GetString("HomePopularMeditations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended For You.
        /// </summary>
        public static string HomeRecommended {
            get {
                return ResourceManager.GetString("HomeRecommended", resourceCulture);
            }
        }
    }
}
