// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SilentMoonApp.Infrastructure.Persistence.Contexts;

#nullable disable

namespace SilentMoonApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260831021006_IsRecommended_IsDailythought_IsPopular_Properities_was_added_into_Courses_Table")]
    partial class IsRecommended_IsDailythought_IsPopular_Properities_was_added_into_Courses_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("CategoryTypeId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("IconFileId")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("IconFileId")
                        .IsUnique()
                        .HasFilter("\"IconFileId\" IS NOT NULL");

                    b.HasIndex("CategoryTypeId", "Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.CategoryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("CategoryTypes", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("CoverImageFileId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<int>("DurationSec")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsDailyThought")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CoverImageFileId")
                        .IsUnique();

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsDailyThought");

                    b.HasIndex("IsFeatured");

                    b.HasIndex("IsPopular");

                    b.HasIndex("IsRecommended");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.CourseFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId", "CourseId")
                        .IsUnique();

                    b.ToTable("CourseFavorites", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Files.AudioFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("DurationSec")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("StorageProvider")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("NVARCHAR2(1024)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("UploadedFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerName", "StoredFileName")
                        .IsUnique();

                    b.ToTable("AudioFiles", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Files.ImageFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.Property<int?>("Height")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("StorageProvider")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("NVARCHAR2(1024)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("UploadedFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)");

                    b.Property<int?>("Width")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ContainerName", "StoredFileName")
                        .IsUnique();

                    b.ToTable("ImageFiles", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("IpAddress")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("ReplacedTokenId")
                        .HasColumnType("RAW(16)");

                    b.Property<int?>("RevocationReason")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("UserAgent")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("ReplacedTokenId")
                        .IsUnique()
                        .HasFilter("\"ReplacedTokenId\" IS NOT NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Name")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid?>("AvatarImageFileId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("LockoutEndAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<int>("UserStatus")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarImageFileId")
                        .IsUnique()
                        .HasFilter("[AvatarImageFileId] IS NOT NULL");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasFilter("[UserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Identity.UserExternalProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<int>("Provider")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUserId")
                        .IsUnique();

                    b.ToTable("UserExternalProviders");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Narrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Narrators", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("AudioFileId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid?>("CoverImageFileId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BOOLEAN");

                    b.Property<Guid>("NarratorId")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("Order")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("AudioFileId")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("CoverImageFileId")
                        .IsUnique()
                        .HasFilter("\"CoverImageFileId\" IS NOT NULL");

                    b.HasIndex("NarratorId");

                    b.HasIndex("CourseId", "Order")
                        .IsUnique();

                    b.ToTable("Tracks", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.TrackProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("Completed")
                        .HasColumnType("BOOLEAN");

                    b.Property<int>("PositionSec")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.HasIndex("UserId", "TrackId")
                        .IsUnique();

                    b.ToTable("TrackProgresses", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.UserTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserId", "TopicId")
                        .IsUnique();

                    b.ToTable("UserTopics", (string)null);
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<int>("DaysOfWeek")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("BOOLEAN");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("INTERVAL DAY(8) TO SECOND(7)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(7) WITH TIME ZONE");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Category", b =>
                {
                    b.HasOne("SilentMoonApp.Domain.Entities.CategoryType", "CategoryType")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SilentMoonApp.Domain.Entities.Files.ImageFile", "IconFile")
                        .WithOne()
                        .HasForeignKey("SilentMoonApp.Domain.Entities.Category", "IconFileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CategoryType");

                    b.Navigation("IconFile");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Course", b =>
                {
                    b.HasOne("SilentMoonApp.Domain.Entities.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SilentMoonApp.Domain.Entities.Files.ImageFile", "CoverImageFile")
                        .WithOne()
                        .HasForeignKey("SilentMoonApp.Domain.Entities.Course", "CoverImageFileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CoverImageFile");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.CourseFavorite", b =>
                {
                    b.HasOne("SilentMoonApp.Domain.Entities.Course", "Course")
                        .WithMany("CourseFavorites")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SilentMoonApp.Domain.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("SilentMoonApp.Domain.Entities.Identity.RefreshToken", null)
                        .WithOne()
                        .HasForeignKey("SilentMoonApp.Domain.Entities.Identity.RefreshToken", "ReplacedTokenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SilentMoonApp.Domain.Entities.Identity.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Identity.User", b =>
                {
                    b.HasOne("SilentMoonApp.Domain.Entities.Files.ImageFile", "AvatarImageFile")
                        .WithOne()
                        .HasForeignKey("SilentMoonApp.Domain.Entities.Identity.User", "AvatarImageFileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AvatarImageFile");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Identity.UserExternalProvider", b =>
                {
                    b.HasOne("SilentMoonApp.Domain.Entities.Identity.User", "User")
                        .WithMany("UserExternalProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Identity.UserRole", b =>
                {
                    b.HasOne("SilentMoonApp.Domain.Entities.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SilentMoonApp.Domain.Entities.Identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Track", b =>
                {
                    b.HasOne("SilentMoonApp.Domain.Entities.Files.AudioFile", "AudioFile")
                        .WithOne()
                        .HasForeignKey("SilentMoonApp.Domain.Entities.Track", "AudioFileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SilentMoonApp.Domain.Entities.Course", "Course")
                        .WithMany("Tracks")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SilentMoonApp.Domain.Entities.Files.ImageFile", "CoverImageFile")
                        .WithOne()
                        .HasForeignKey("SilentMoonApp.Domain.Entities.Track", "CoverImageFileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SilentMoonApp.Domain.Entities.Narrator", "Narrator")
                        .WithMany("Tracks")
                        .HasForeignKey("NarratorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AudioFile");

                    b.Navigation("Course");

                    b.Navigation("CoverImageFile");

                    b.Navigation("Narrator");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.TrackProgress", b =>
                {
                    b.HasOne("SilentMoonApp.Domain.Entities.Track", "Track")
                        .WithMany("TrackProgresses")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SilentMoonApp.Domain.Entities.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Track");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.UserTopic", b =>
                {
                    b.HasOne("SilentMoonApp.Domain.Entities.Topic", "Topic")
                        .WithMany("UserTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SilentMoonApp.Domain.Entities.Identity.User", "User")
                        .WithMany("UserTopics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Reminder", b =>
                {
                    b.HasOne("SilentMoonApp.Domain.Entities.Identity.User", "User")
                        .WithMany("Reminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.CategoryType", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Course", b =>
                {
                    b.Navigation("CourseFavorites");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Identity.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Reminders");

                    b.Navigation("UserExternalProviders");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTopics");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Narrator", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Topic", b =>
                {
                    b.Navigation("UserTopics");
                });

            modelBuilder.Entity("SilentMoonApp.Domain.Entities.Track", b =>
                {
                    b.Navigation("TrackProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
